### PR TITLE
Use long sizes only for big packages

### LINKED ISSUE #148: Compatability with CentOS 7
By using the same library and snippet as in #147 I get [`libdummyadd.rpm`](https://github.com/rpm-rs/rpm/files/11604258/libdummyadd.zip). When I try to install it on CentOS 7, I get the following error:
```
Running transaction
Error unpacking rpm package libdummyadd-0.1.0-1.x86_64
  Installing : libdummyadd-0.1.0-1.x86_64                                   1/1 
error: unpacking of archive failed on file /usr/lib64/libdummyadd.so;6476433e: cpio: Digest mismatch
  Verifying  : libdummyadd-0.1.0-1.x86_64                                   1/1 

Failed:
  libdummyadd.x86_64 0:0.1.0-1    
```

`rpm -v --checksig libdummyadd.rpm` returns:
```
libdummyadd.rpm:
    Header SHA1 digest: OK (77492d16c6b099e0bc74cc864fe316c7f7dfe6b6)
    MD5 digest: OK (7decf15b91517ed4fb2edc616914dbe2)
```

Running `rpm -qp --xml libdummyadd.rpm` I get:
<details> 
  <summary>Expand</summary>

```xml
<rpmHeader>
  <rpmTag name="Headeri18ntable">
	<string>C</string>
  </rpmTag>
  <rpmTag name="Sigmd5">
	<base64>CcK1Fb+YZqLtn6QTsd0GRQ==
</base64>
  </rpmTag>
  <rpmTag name="Sha1header">
	<string>f4e9822feed5995e8234a1525bbcb742955f7937</string>
  </rpmTag>
  <rpmTag name="Longsigsize">
	<integer>15401</integer>
  </rpmTag>
  <rpmTag name="Name">
	<string>libdummyadd</string>
  </rpmTag>
  <rpmTag name="Version">
	<string>0.1.0</string>
  </rpmTag>
  <rpmTag name="Release">
	<string>1</string>
  </rpmTag>
  <rpmTag name="Epoch">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Summary">
	<string>Dummy library for testing RPM generation</string>
  </rpmTag>
  <rpmTag name="Description">
	<string>Dummy library for testing RPM generation</string>
  </rpmTag>
  <rpmTag name="Buildtime">
	<integer>1685472520</integer>
  </rpmTag>
  <rpmTag name="Buildhost">
	<string>host</string>
  </rpmTag>
  <rpmTag name="Vendor">
	<string>NA</string>
  </rpmTag>
  <rpmTag name="License">
	<string>UNLICENSE</string>
  </rpmTag>
  <rpmTag name="Group">
	<string>Unspecified</string>
  </rpmTag>
  <rpmTag name="Os">
	<string>linux</string>
  </rpmTag>
  <rpmTag name="Arch">
	<string>x86_64</string>
  </rpmTag>
  <rpmTag name="Filemodes">
	<integer>33188</integer>
  </rpmTag>
  <rpmTag name="Filerdevs">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Filemtimes">
	<integer>1685446558</integer>
  </rpmTag>
  <rpmTag name="Filedigests">
	<string>0ac32c56c20ac2e18885b817ccf1fdf59221ed0c6c410126e97c2c3c1524aca7</string>
  </rpmTag>
  <rpmTag name="Filelinktos">
	<string/>
  </rpmTag>
  <rpmTag name="Fileflags">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Fileusername">
	<string>root</string>
  </rpmTag>
  <rpmTag name="Filegroupname">
	<string>root</string>
  </rpmTag>
  <rpmTag name="Sourcerpm">
	<string>(none)</string>
  </rpmTag>
  <rpmTag name="Fileverifyflags">
	<integer>4026565119</integer>
  </rpmTag>
  <rpmTag name="Providename">
	<string>libdummyadd</string>
	<string>libdummyadd(x86_64)</string>
  </rpmTag>
  <rpmTag name="Requireflags">
	<integer>16777224</integer>
	<integer>16777224</integer>
	<integer>16777224</integer>
  </rpmTag>
  <rpmTag name="Requirename">
	<string>rpmlib(CompressedFileNames)</string>
	<string>rpmlib(FileDigests)</string>
	<string>rpmlib(PayloadFilesHavePrefix)</string>
  </rpmTag>
  <rpmTag name="Requireversion">
	<string>3.0.4-1</string>
	<string>4.6.0-1</string>
	<string>4.0-1</string>
  </rpmTag>
  <rpmTag name="Filedevices">
	<integer>1</integer>
  </rpmTag>
  <rpmTag name="Fileinodes">
	<integer>1</integer>
  </rpmTag>
  <rpmTag name="Filelangs">
	<string/>
  </rpmTag>
  <rpmTag name="Provideflags">
	<integer>8</integer>
	<integer>8</integer>
  </rpmTag>
  <rpmTag name="Provideversion">
	<string>0.1.0</string>
	<string>0.1.0</string>
  </rpmTag>
  <rpmTag name="Dirindexes">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Basenames">
	<string>libdummyadd.so</string>
  </rpmTag>
  <rpmTag name="Dirnames">
	<string>/usr/lib64/</string>
  </rpmTag>
  <rpmTag name="Payloadformat">
	<string>cpio</string>
  </rpmTag>
  <rpmTag name="Longfilesizes">
	<integer>13768</integer>
  </rpmTag>
  <rpmTag name="Longsize">
	<integer>13768</integer>
  </rpmTag>
  <rpmTag name="Filedigestalgo">
	<integer>8</integer>
  </rpmTag>
  <rpmTag name="(unknown)">
	<string>utf-8</string>
  </rpmTag>
  <rpmTag name="(unknown)">
	<string>7806d7ab151d7bb9be3e771f03f6e5b35543322d5f9130d7009cda1f8e3542ac</string>
  </rpmTag>
  <rpmTag name="(unknown)">
	<integer>8</integer>
  </rpmTag>
  <rpmTag name="(unknown)">
	<string>7806d7ab151d7bb9be3e771f03f6e5b35543322d5f9130d7009cda1f8e3542ac</string>
  </rpmTag>
</rpmHeader>
```
</details>

It looks like the older RPM version (4.11.3) used by CentOS 7 does not recognize the payload tags (Encoding, Payloaddigest, Payloaddigestalgo) which results in the digest check failure.

Packet generated by `cargo-generate-rpm` using `rpm v0.9.0-alpha.1` can be installed just fine (but it suffers from #147). Here is output of `rpm -qp --xml` for it:
<details> 
  <summary>Expand</summary>

```xml
<rpmHeader>
  <rpmTag name="Headeri18ntable">
	<string>C</string>
  </rpmTag>
  <rpmTag name="Sigsize">
	<integer>6924</integer>
  </rpmTag>
  <rpmTag name="Sigmd5">
	<base64>IqqkWf92M+TU+/kvoH7blw==
</base64>
  </rpmTag>
  <rpmTag name="Sha1header">
	<string>ab8a051feb21c26a5ae615495e0e15d76c1b71e7</string>
  </rpmTag>
  <rpmTag name="Name">
	<string>libdummyadd</string>
  </rpmTag>
  <rpmTag name="Version">
	<string>0.1.0</string>
  </rpmTag>
  <rpmTag name="Release">
	<string>1</string>
  </rpmTag>
  <rpmTag name="Epoch">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Summary">
	<string>Dummy library for testing RPM generation</string>
  </rpmTag>
  <rpmTag name="Description">
	<string>Dummy library for testing RPM generation</string>
  </rpmTag>
  <rpmTag name="Size">
	<integer>5664</integer>
  </rpmTag>
  <rpmTag name="License">
	<string>UNLICENSE</string>
  </rpmTag>
  <rpmTag name="Group">
	<string>Unspecified</string>
  </rpmTag>
  <rpmTag name="Os">
	<string>linux</string>
  </rpmTag>
  <rpmTag name="Arch">
	<string>x86_64</string>
  </rpmTag>
  <rpmTag name="Filesizes">
	<integer>5664</integer>
  </rpmTag>
  <rpmTag name="Filemodes">
	<integer>33188</integer>
  </rpmTag>
  <rpmTag name="Filerdevs">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Filemtimes">
	<integer>1685473437</integer>
  </rpmTag>
  <rpmTag name="Filedigests">
	<string>6fef19b830770d7ebc3d4de02a6ebaccb1860b2a41277f230e164be0626f4074</string>
  </rpmTag>
  <rpmTag name="Filelinktos">
	<string/>
  </rpmTag>
  <rpmTag name="Fileflags">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Fileusername">
	<string>root</string>
  </rpmTag>
  <rpmTag name="Filegroupname">
	<string>root</string>
  </rpmTag>
  <rpmTag name="Sourcerpm">
	<string>(none)</string>
  </rpmTag>
  <rpmTag name="Fileverifyflags">
	<integer>4294967295</integer>
  </rpmTag>
  <rpmTag name="Providename">
	<string>libdummyadd</string>
	<string>libdummyadd(x86_64)</string>
  </rpmTag>
  <rpmTag name="Requireflags">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Requirename">
	<string>/bin/sh</string>
  </rpmTag>
  <rpmTag name="Requireversion">
	<string/>
  </rpmTag>
  <rpmTag name="Filedevices">
	<integer>1</integer>
  </rpmTag>
  <rpmTag name="Fileinodes">
	<integer>1</integer>
  </rpmTag>
  <rpmTag name="Filelangs">
	<string/>
  </rpmTag>
  <rpmTag name="Provideflags">
	<integer>8</integer>
	<integer>8</integer>
  </rpmTag>
  <rpmTag name="Provideversion">
	<string>0.1.0</string>
	<string>0.1.0</string>
  </rpmTag>
  <rpmTag name="Dirindexes">
	<integer>0</integer>
  </rpmTag>
  <rpmTag name="Basenames">
	<string>libdummyadd.so</string>
  </rpmTag>
  <rpmTag name="Dirnames">
	<string>/usr/lib64/</string>
  </rpmTag>
  <rpmTag name="Payloadformat">
	<string>cpio</string>
  </rpmTag>
  <rpmTag name="Filedigestalgo">
	<integer>8</integer>
  </rpmTag>
</rpmHeader>
```
</details>

Is it possible to generate CentOS 7 compatible packet using rpm v0.11?

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #148 and fixes several clippy lints.

### CODE REVIEW

**Comment by dralley** [comment]
See my latest comment https://github.com/rpm-rs/rpm/issues/148#issuecomment-1570259296

I think rather than making the user specify `small_package()`, we should just fall back to using the old tags when the sizes all fit into 32 bits.

**Comment by dralley** [comment]
Actually since you have all the branches already just switch it from setting `small_package` based on user input to just determining it based on the sizes.

**Comment by newpavlov** [comment]
I wonder if RPM allows to mix long and short sizes in one packet, i.e. what should we generate with `combined_file_sizes` > 4 GiB, but all files smaller than the limit.

File: src/rpm/builder.rs [hunk 1]
```diff
@@ -746,11 +747,20 @@ impl RPMBuilder {
                 offset,
                 IndexData::I18NString(vec![self.desc]),
             ),
-            IndexEntry::new(
-                IndexTag::RPMTAG_LONGSIZE,
-                offset,
-                IndexData::Int64(vec![combined_file_sizes]),
-            ),
+            match combined_file_sizes.try_into() {
```
Comment (dralley) [inline src/rpm/builder.rs:750]: Does this actually build?  Interesting

I would prefer something like this, having already done the calculation

```
if small_package {
              IndexEntry::new(
                  IndexTag::RPMTAG_SIZE,
                offset,
                IndexData::Int64(vec![combined_file_sizes]),
                    IndexEntry::new(IndexTag::RPMTAG_SIZE, offset, IndexData::Int32(vec![size]))
            ),
} else {
              IndexEntry::new(
                  IndexTag::RPMTAG_LONGSIZE,
                  offset,
                  IndexData::Int64(vec![combined_file_sizes]),
              )
}

File: src/rpm/headers/signature_builder.rs [hunk 2]
```diff
@@ -57,14 +57,17 @@ where
...
+                IndexData::Int32(vec![size]),
+            ),
+            Err(_) => (
                 IndexSignatureTag::RPMSIGTAG_LONGSIZE,
-                0i32, // externally filled
                 IndexData::Int64(vec![headers_plus_payload_size as u64]),
             ),
-        );
+        };
+        self.entries.insert(0, IndexEntry::new(tag, 0i32, data));
```
Comment (dralley) [inline src/rpm/headers/signature_builder.rs:70]: I'm OK with this approach too if you want to use it above.

**Review by dralley — CHANGES_REQUESTED** [review]

File: src/rpm/builder.rs [hunk 3]
```diff
@@ -707,6 +707,7 @@ impl RPMBuilder {
         }
 
         let offset = 0;
+        let small_packet;
```
[the remark this answers is not in the document]
Comment (dralley) [reply src/rpm/builder.rs:710]: also `small_packet` -> `small_package`

[the remark this answers is not in the document]
Comment (newpavlov) [reply src/rpm/builder.rs:710]: I did it to remove unnecessary unwraps later in code. Note that this variable can not be used without initialization unlike in C.

 If you want to perform calculation as early as possible, I think something like this would be better:
```rust
let (small_package, combined_file_sizes_entry) = match combined_file_sizes.try_into() {
    Ok(size) => (
        true,
        IndexEntry::new(IndexTag::RPMTAG_SIZE, offset, IndexData::Int32(vec![size])),
    ),
    Err(_) => (
        false,
        IndexEntry::new(
            IndexTag::RPMTAG_LONGSIZE,
            offset,
            IndexData::Int64(vec![combined_file_sizes]),
        ),
    ),
};
```

File: src/rpm/builder.rs [hunk 4]
```diff
@@ -707,6 +707,20 @@ impl RPMBuilder {
         }
 
         let offset = 0;
+        let (small_package, combined_file_sizes_entry) = match combined_file_sizes.try_into() {
```
Comment (dralley) [inline src/rpm/builder.rs:710]: I would still rather the small package check be separate personally.

**Comment by dralley** [comment]
Add a changelog also

File: src/rpm/builder.rs (hunk 4 above)
Comment (newpavlov) [reply src/rpm/builder.rs:710]: Then we would have `combined_file_sizes.try_into().unwrap()` later in code, which is implicitly connected to the `small_package` calculation. In this code the connection is explicit and robust, for example, if hypothetically you will switch from `u32` to `i32` in future, it will continue to work correctly, while with the separate calculation you would have to remember to update it.

Either way, I don't care about it too much, so I can change it if you like it more.

File: CHANGELOG.md [hunk 5]
```diff
@@ -5,6 +5,8 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ## [Unreleased]
+### Fixed
+- CentOS 7 support by using long sizes only for packets bigger than 4 GiB
```
Comment (dralley) [inline CHANGELOG.md:9]: packets -> packages

Could you add some whitespace between headings also?

File: src/rpm/builder.rs [hunk 6]
```diff
@@ -746,11 +747,21 @@ impl RPMBuilder {
...
-                offset,
-                IndexData::Int64(vec![combined_file_sizes]),
-            ),
+            if small_package {
+                IndexEntry::new(
+                    IndexTag::RPMTAG_SIZE,
+                    offset,
+                    IndexData::Int32(vec![combined_file_sizes
+                        .try_into()
+                        .expect("combined_file_sizes is smaller than 4 GiB")]),
```
Comment (dralley) [inline src/rpm/builder.rs:756]: Just using `as` would be safe here as you've already checked the size.  If you prefer the falliable methods, I think this message is actually backwards, the value is bigger than expected.

File: src/rpm/builder.rs [hunk 7]
```diff
@@ -804,12 +815,18 @@ impl RPMBuilder {
 
         // if we have an empty RPM, we have to leave out all file related index entries.
         if !self.files.is_empty() {
+            let (tag, data) = if small_package {
+                let file_sizes = file_sizes
+                    .into_iter()
+                    .map(u32::try_from)
+                    .collect::<Result<_, _>>()
+                    .expect("combined_file_sizes is smaller than 4 GiB");
```
Comment (dralley) [inline src/rpm/builder.rs:823]: In this instance falliability is actually proper, but we shouldn't panic.  `if let Ok(file_sizes) = ... else`

Comment (newpavlov) [reply src/rpm/builder.rs:823]: IIUC it should never panic since `combined_file_sizes` is a sum of all file sizes, thus if it's smaller than 4 GiB, it means that it's true for all files as well.

File: src/rpm/builder.rs (hunk 6 above)
Comment (newpavlov) [reply src/rpm/builder.rs:756]: Unwrapping provides a safety net in case of potential mistakes, so it's better to keep it.

File: CHANGELOG.md (hunk 5 above)
Comment (newpavlov) [reply CHANGELOG.md:11]: Done.

File: src/rpm/builder.rs (hunk 7 above)
Comment (dralley) [reply src/rpm/builder.rs:823]: The message is backwards here also

File: src/rpm/builder.rs (hunk 6 above)
Comment (newpavlov) [reply src/rpm/builder.rs:756]: As per [std docs](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style) `expect` message describes the reason we expect the `Result` should be `Ok`. I will update the message to use "should be".

**Comment by dralley** [comment]
Thanks for the investigation and fix!
