### PR TITLE
Make Error Send + Sync (fixes #191)

### LINKED ISSUE #191: Support `Sync` trait for `rpm::Error`
I would like to use a return type equal to `anyhow::Result<RPMFile>`  for a multi-threaded code and I face the following issue:

```
        let header = rpm::PackageMetadata::parse(&mut buf_reader).context("RPM parsing failed")?;
```

```
error[E0599]: the method `context` exists for enum `Result<PackageMetadata, Error>`, but its trait bounds were not satisfied
   --> src/main.rs:140:67
    |
140 |         let header = rpm::PackageMetadata::parse(&mut buf_reader).context("RPM parsing failed")?;
    |                                                                   ^^^^^^^ method cannot be called on `Result<PackageMetadata, Error>` due to unsatisfied trait bounds
    |
   ::: /home/marxin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | --------------------- doesn't satisfy `_: Context<PackageMetadata, Error>`
    |
   ::: /home/marxin/Programming/rpm-rs/src/errors.rs:9:1
    |
9   | pub enum Error {
    | --------------
    | |
    | doesn't satisfy `rpm::Error: Sync`
    | doesn't satisfy `rpm::Error: anyhow::context::ext::StdError`
    | doesn't satisfy `rpm::Error: std::marker::Send`
    |
    = note: the following trait bounds were not satisfied:
            `rpm::Error: anyhow::context::ext::StdError`
            which is required by `Result<PackageMetadata, rpm::Error>: anyhow::Context<PackageMetadata, rpm::Error>`
            `rpm::Error: std::marker::Send`
            which is required by `Result<PackageMetadata, rpm::Error>: anyhow::Context<PackageMetadata, rpm::Error>`
            `rpm::Error: Sync`
            which is required by `Result<PackageMetadata, rpm::Error>: anyhow::Context<PackageMetadata, rpm::Error>`
```

### PR DESCRIPTION
**Pull request by udoprog**
Uses a different approach than the ones in comments of #191. Most errors do not need to be boxed, and introducing two error variants instead of having one very generic one (with static details) ends up not being too bad.

### 📜 Checklist

- [x] Commits are cleanly separated and have useful messages
- [x] A changelog entry or entries has been added to CHANGELOG.md
- [x] Documentation is thorough
- [x] Test coverage is excellent and passes
- [ ] Works when tests are run `--all-features` enabled

### CODE REVIEW

File: src/errors.rs [hunk 1]
```diff
@@ -110,3 +122,8 @@ impl From<TimestampError> for Error {
         Error::TimestampConv(error)
     }
 }
+
+const _: () = {
+    const fn assert_send_sync<T: Send + Sync>() {}
+    assert_send_sync::<Error>();
+};
```
Comment (dralley) [inline src/errors.rs:129]: What is this?

Comment (udoprog) [reply src/errors.rs:129]: It asserts that the `Error` type implements `Send + Sync` at compile time.

Comment (dralley) [reply src/errors.rs:129]: Can we do this in a test rather than in the source code?  And leave documentation to that effect?

Comment (udoprog) [reply src/errors.rs:129]: This is just FYI, I don't particularly oppose moving it to a test if that's what you want to do.

Since these are auto traits, it could mean that the `Error` type loses its `Send + Sync`-ness due to an upstream change. You might want to keep this as an earlier, more appropriately placed compilation error to catch that.

Comment (dralley) [reply src/errors.rs:129]: Well, let's at least document what it is doing

File: CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## Unreleased
 
+### Changed
+
+- `Error` now implements `Send + Sync`.
```
Comment (dralley) [inline CHANGELOG.md:12]: Do you think it would be useful to extend this with

> (therefore, `Result<Package, Error>` now implements `Send + Sync`)

File: src/errors.rs [hunk 3]
```diff
@@ -110,3 +122,8 @@ impl From<TimestampError> for Error {
         Error::TimestampConv(error)
     }
 }
+
```
Comment (udoprog) [inline src/errors.rs:125]:
```suggestion
// Assert at compile-time that Error implements Send and Sync.
```

File: CHANGELOG.md (hunk 2 above)
Comment (udoprog) [inline CHANGELOG.md:12]:
```suggestion
- `Error` now implements `Send + Sync` (therefore, `Result<Package, Error>` now implements `Send + Sync`).
```

**Review by dralley — APPROVED** [review]
